// Code generated by MockGen. DO NOT EDIT.
// Source: ../internal/domain/repositories.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entities "github.com/SemgaTeam/sso/internal/entities"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddCredential mocks base method.
func (m *MockUserRepository) AddCredential(credential *entities.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredential", credential)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCredential indicates an expected call of AddCredential.
func (mr *MockUserRepositoryMockRecorder) AddCredential(credential interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredential", reflect.TypeOf((*MockUserRepository)(nil).AddCredential), credential)
}

// AddIdentity mocks base method.
func (m *MockUserRepository) AddIdentity(identity *entities.Identity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIdentity", identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIdentity indicates an expected call of AddIdentity.
func (mr *MockUserRepositoryMockRecorder) AddIdentity(identity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIdentity", reflect.TypeOf((*MockUserRepository)(nil).AddIdentity), identity)
}

// ByEmail mocks base method.
func (m *MockUserRepository) ByEmail(email string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByEmail", email)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByEmail indicates an expected call of ByEmail.
func (mr *MockUserRepositoryMockRecorder) ByEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByEmail", reflect.TypeOf((*MockUserRepository)(nil).ByEmail), email)
}

// ByID mocks base method.
func (m *MockUserRepository) ByID(id uuid.UUID) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByID", id)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByID indicates an expected call of ByID.
func (mr *MockUserRepositoryMockRecorder) ByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByID", reflect.TypeOf((*MockUserRepository)(nil).ByID), id)
}

// ByIdentity mocks base method.
func (m *MockUserRepository) ByIdentity(itype, external_id, issuer string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByIdentity", itype, external_id, issuer)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ByIdentity indicates an expected call of ByIdentity.
func (mr *MockUserRepositoryMockRecorder) ByIdentity(itype, external_id, issuer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByIdentity", reflect.TypeOf((*MockUserRepository)(nil).ByIdentity), itype, external_id, issuer)
}

// Save mocks base method.
func (m *MockUserRepository) Save(user *entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserRepositoryMockRecorder) Save(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRepository)(nil).Save), user)
}

// MockHashRepository is a mock of HashRepository interface.
type MockHashRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHashRepositoryMockRecorder
}

// MockHashRepositoryMockRecorder is the mock recorder for MockHashRepository.
type MockHashRepositoryMockRecorder struct {
	mock *MockHashRepository
}

// NewMockHashRepository creates a new mock instance.
func NewMockHashRepository(ctrl *gomock.Controller) *MockHashRepository {
	mock := &MockHashRepository{ctrl: ctrl}
	mock.recorder = &MockHashRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashRepository) EXPECT() *MockHashRepositoryMockRecorder {
	return m.recorder
}

// HashPassword mocks base method.
func (m *MockHashRepository) HashPassword(raw string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", raw)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockHashRepositoryMockRecorder) HashPassword(raw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockHashRepository)(nil).HashPassword), raw)
}

// PasswordValid mocks base method.
func (m *MockHashRepository) PasswordValid(raw, hashed string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordValid", raw, hashed)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PasswordValid indicates an expected call of PasswordValid.
func (mr *MockHashRepositoryMockRecorder) PasswordValid(raw, hashed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordValid", reflect.TypeOf((*MockHashRepository)(nil).PasswordValid), raw, hashed)
}
